#!/usr/bin/env python3
# -*- coding: utf-8 -*-

name: unahug
channels:
  - defaults
dependencies:
  - python=3.7.16
  - pip
  - pip:
    - pandas==1.3.5
    - numpy==1.21.6
    - gym==0.19.0
    - matplotlib==3.5.3
    - pyyaml==6.0
    - pygame==2.5.0
    - scipy==1.7.3
    - spyder==5.1.5
    - einops==0.6.0
    - cpprb
    - tqdm


